site_name: Documentação de Arquitetura CCM
site_url: https://edcastanha.github.io/desafio-ccm-Arquitetura/
docs_dir: docs
site_author: Edson Lourenco
site_description: >-
  Repositorio teste de arquitetura para desenvolvimento Python.

# Copyright
copyright: Copyright &copy; 2025 Edson Lourenco

# Configuration
theme:
  name: material
  nav_style: dark
  language: pt-BR
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

plugins:
  - search


nav:
  - Início: index.md
  - Decisão de Arquitetura (ADR):
    - adrs/arquitetura-geral.md
  - Documentos de Detalhamento:
    - fluxo-de-dados.md
    - funcionalidades.md
    - seguranca.md
  - Sobre Edson Lourenço:
    - sobre.md
  - Licença: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edcastanha/desafio-ccm-Arquitetura